#!/bin/bash

# Running Page 2.0 - Wiki Sync Script
# Syncs local wiki files to GitHub Wiki

set -e

echo "🚀 Running Page 2.0 - Wiki Sync"
echo "================================"

# Configuration
REPO_URL="https://github.com/oiahoon/running2.0.wiki.git"
WIKI_DIR="./wiki"
TEMP_DIR="/tmp/running-page-wiki"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Check if wiki directory exists
if [ ! -d "$WIKI_DIR" ]; then
    echo -e "${RED}❌ Wiki directory not found: $WIKI_DIR${NC}"
    exit 1
fi

# Count wiki files
WIKI_FILES=$(find "$WIKI_DIR" -name "*.md" | wc -l)
echo -e "${BLUE}📚 Found $WIKI_FILES wiki files${NC}"

# List wiki files
echo -e "${YELLOW}📄 Wiki files:${NC}"
find "$WIKI_DIR" -name "*.md" -exec basename {} \; | sort

# Clean up temp directory
if [ -d "$TEMP_DIR" ]; then
    echo -e "${YELLOW}🧹 Cleaning up temp directory${NC}"
    rm -rf "$TEMP_DIR"
fi

# Clone GitHub Wiki repository
echo -e "${BLUE}📥 Cloning GitHub Wiki repository${NC}"
git clone "$REPO_URL" "$TEMP_DIR" 2>/dev/null || {
    echo -e "${YELLOW}⚠️  Wiki repository not found, creating new one${NC}"
    mkdir -p "$TEMP_DIR"
    cd "$TEMP_DIR"
    git init
    git remote add origin "$REPO_URL"
}

# Copy wiki files
echo -e "${BLUE}📋 Copying wiki files${NC}"
cp "$WIKI_DIR"/*.md "$TEMP_DIR/" 2>/dev/null || {
    echo -e "${RED}❌ No .md files found in wiki directory${NC}"
    exit 1
}

# Navigate to temp directory
cd "$TEMP_DIR"

# Configure git if needed
git config user.name "Wiki Sync Bot" 2>/dev/null || true
git config user.email "wiki@running-page.dev" 2>/dev/null || true

# Add and commit changes
echo -e "${BLUE}📝 Committing changes${NC}"
git add .

# Check if there are changes to commit
if git diff --staged --quiet; then
    echo -e "${GREEN}✅ No changes to commit - Wiki is up to date${NC}"
else
    # Create commit message
    COMMIT_MSG="📚 Update wiki documentation

- Updated $(date '+%Y-%m-%d %H:%M:%S')
- Synced from local wiki directory
- Total files: $WIKI_FILES

Auto-generated by wiki sync script"

    git commit -m "$COMMIT_MSG"
    
    # Push changes
    echo -e "${BLUE}🚀 Pushing to GitHub Wiki${NC}"
    git push origin master 2>/dev/null || git push -u origin master
    
    echo -e "${GREEN}✅ Wiki sync completed successfully${NC}"
fi

# Clean up
echo -e "${YELLOW}🧹 Cleaning up${NC}"
cd - > /dev/null
rm -rf "$TEMP_DIR"

echo -e "${GREEN}🎉 Wiki sync process completed${NC}"
echo -e "${BLUE}📖 View wiki at: https://github.com/oiahoon/running2.0/wiki${NC}"
