#!/bin/bash

# Running Page 2.0 - Wiki Sync Script
# Syncs local wiki files to GitHub Wiki

set -e

echo "Deploy Running Page 2.0 - Wiki Sync"
echo "================================"

# Configuration
REPO_SSH="git@github.com:oiahoon/running2.0.wiki.git"
REPO_HTTPS="https://github.com/oiahoon/running2.0.wiki.git"
WIKI_DIR="./wiki"
TEMP_DIR="/tmp/running-page-wiki"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Check if wiki directory exists
if [ ! -d "$WIKI_DIR" ]; then
    echo -e "${RED}Error Wiki directory not found: $WIKI_DIR${NC}"
    exit 1
fi

# Count wiki files
WIKI_FILES=$(find "$WIKI_DIR" -name "*.md" | wc -l)
echo -e "${BLUE}Docs Found $WIKI_FILES wiki files${NC}"

# List wiki files
echo -e "${YELLOW}File Wiki files:${NC}"
find "$WIKI_DIR" -name "*.md" -exec basename {} \; | sort

# Clean up temp directory
if [ -d "$TEMP_DIR" ]; then
    echo -e "${YELLOW}Cleanup Cleaning up temp directory${NC}"
    rm -rf "$TEMP_DIR"
fi

# Try SSH first, then HTTPS
echo -e "${BLUE}Download Cloning GitHub Wiki repository${NC}"
if git clone "$REPO_SSH" "$TEMP_DIR" 2>/dev/null; then
    echo -e "${GREEN}OK Cloned using SSH${NC}"
    REPO_URL="$REPO_SSH"
elif git clone "$REPO_HTTPS" "$TEMP_DIR" 2>/dev/null; then
    echo -e "${GREEN}OK Cloned using HTTPS${NC}"
    REPO_URL="$REPO_HTTPS"
else
    echo -e "${YELLOW}Warning  Wiki repository not found, creating new one${NC}"
    mkdir -p "$TEMP_DIR"
    cd "$TEMP_DIR"
    git init
    # Try SSH first for new repo
    if ssh -T git@github.com 2>&1 | grep -q "successfully authenticated"; then
        git remote add origin "$REPO_SSH"
        REPO_URL="$REPO_SSH"
        echo -e "${GREEN}OK Using SSH for new repository${NC}"
    else
        git remote add origin "$REPO_HTTPS"
        REPO_URL="$REPO_HTTPS"
        echo -e "${YELLOW}Warning  Using HTTPS - you may need to authenticate${NC}"
    fi
fi

# Copy wiki files
echo -e "${BLUE}List Copying wiki files${NC}"
cp "$WIKI_DIR"/*.md "$TEMP_DIR/" 2>/dev/null || {
    echo -e "${RED}Error No .md files found in wiki directory${NC}"
    exit 1
}

# Navigate to temp directory
cd "$TEMP_DIR"

# Configure git if needed
git config user.name "Wiki Sync Bot" 2>/dev/null || true
git config user.email "wiki@running-page.dev" 2>/dev/null || true

# Add and commit changes
echo -e "${BLUE}Commit Committing changes${NC}"
git add .

# Check if there are changes to commit
if git diff --staged --quiet; then
    echo -e "${GREEN}OK No changes to commit - Wiki is up to date${NC}"
else
    # Create commit message
    COMMIT_MSG="Docs Update wiki documentation

- Updated $(date '+%Y-%m-%d %H:%M:%S')
- Synced from local wiki directory
- Total files: $WIKI_FILES

Auto-generated by wiki sync script"

    git commit -m "$COMMIT_MSG"
    
    # Push changes
    echo -e "${BLUE}Deploy Pushing to GitHub Wiki${NC}"
    if git push origin master 2>/dev/null || git push -u origin master 2>/dev/null; then
        echo -e "${GREEN}OK Wiki sync completed successfully${NC}"
    else
        echo -e "${RED}Error Failed to push to GitHub Wiki${NC}"
        echo -e "${YELLOW}Tip Manual sync instructions:${NC}"
        echo -e "${BLUE}1. Go to: https://github.com/oiahoon/running2.0/wiki${NC}"
        echo -e "${BLUE}2. Click 'New Page' or edit existing pages${NC}"
        echo -e "${BLUE}3. Copy content from the following files:${NC}"
        find "$WIKI_DIR" -name "*.md" -exec echo "   - {}" \;
        echo -e "${BLUE}4. Or use GitHub CLI: gh repo clone oiahoon/running2.0.wiki${NC}"
    fi
fi

# Clean up
echo -e "${YELLOW}Cleanup Cleaning up${NC}"
cd - > /dev/null
rm -rf "$TEMP_DIR"

echo -e "${GREEN}Done Wiki sync process completed${NC}"
echo -e "${BLUE}View wiki at: https://github.com/oiahoon/running2.0/wiki${NC}"
