name: Deploy Simple

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Prepare files
      run: |
        echo "Preparing homepage files..."
        mkdir -p site
        
        # Copy homepage files
        cp homepage/index.html site/
        cp homepage/styles.css site/
        cp homepage/script.js site/
        cp homepage/favicon.svg site/
        cp homepage/test.html site/
        
        # Create sitemap
        cat > site/sitemap.xml << 'EOF'
        <?xml version="1.0" encoding="UTF-8"?>
        <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
          <url>
            <loc>https://oiahoon.github.io/running2.0/</loc>
            <lastmod>2024-07-06</lastmod>
            <changefreq>weekly</changefreq>
            <priority>1.0</priority>
          </url>
        </urlset>
        EOF
        
        # Create robots.txt
        cat > site/robots.txt << 'EOF'
        User-agent: *
        Allow: /
        
        Sitemap: https://oiahoon.github.io/running2.0/sitemap.xml
        EOF
        
        echo "Files ready:"
        ls -la site/
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
        force_orphan: true
        
    - name: Done
      run: |
        echo "✅ Deployed to https://oiahoon.github.io/running2.0/"
        echo "Wait 5-10 minutes for GitHub Pages to update"
