name: Test Secrets Configuration

on:
  workflow_dispatch:

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    
    steps:
    - name: Test Strava Secrets
      run: |
        echo "Testing Strava secrets configuration..."
        
        if [ -z "$STRAVA_CLIENT_ID" ]; then
          echo "❌ STRAVA_CLIENT_ID is empty or not set"
        else
          echo "✅ STRAVA_CLIENT_ID is set (length: ${#STRAVA_CLIENT_ID})"
        fi
        
        if [ -z "$STRAVA_CLIENT_SECRET" ]; then
          echo "❌ STRAVA_CLIENT_SECRET is empty or not set"
        else
          echo "✅ STRAVA_CLIENT_SECRET is set (length: ${#STRAVA_CLIENT_SECRET})"
        fi
        
        if [ -z "$STRAVA_REFRESH_TOKEN" ]; then
          echo "❌ STRAVA_REFRESH_TOKEN is empty or not set"
        else
          echo "✅ STRAVA_REFRESH_TOKEN is set (length: ${#STRAVA_REFRESH_TOKEN})"
        fi
        
        echo ""
        echo "Secret names should be exactly:"
        echo "- STRAVA_CLIENT_ID"
        echo "- STRAVA_CLIENT_SECRET" 
        echo "- STRAVA_REFRESH_TOKEN"
        echo ""
        echo "Please check GitHub repository settings:"
        echo "https://github.com/oiahoon/running2.0/settings/secrets/actions"
      env:
        STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
        STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
        STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
